SELECT P.PAYMENT_ID, F.FILM_ID, F.TITLE,
	P.AMOUNT
FROM RENTAL R
RIGHT JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
INNER JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
INNER JOIN FILM F ON F.FILM_ID = I.FILM_ID