WITH T1 AS
	(SELECT C.NAME AS GENRE,
			COUNT(CU.CUSTOMER_ID) AS TOTAL_RENT_DEMAND
		FROM CATEGORY C
		JOIN FILM_CATEGORY FC USING(CATEGORY_ID)
		JOIN FILM F USING(FILM_ID)
		JOIN INVENTORY I USING(FILM_ID)
		JOIN RENTAL R USING(INVENTORY_ID)
		JOIN CUSTOMER CU USING(CUSTOMER_ID)
		GROUP BY 1
		ORDER BY 2 DESC),
	T2 AS
	(SELECT C.NAME AS GENRE,
			SUM(P.AMOUNT) AS TOTAL_SALES
		FROM CATEGORY C
		JOIN FILM_CATEGORY FC USING(CATEGORY_ID)
		JOIN FILM F USING(FILM_ID)
		JOIN INVENTORY I USING(FILM_ID)
		JOIN RENTAL R USING(INVENTORY_ID)
		JOIN PAYMENT P USING(RENTAL_ID)
		GROUP BY 1
		ORDER BY 2 DESC)
SELECT T1.GENRE,
	T1.TOTAL_RENT_DEMAND,
	T2.TOTAL_SALES
FROM T1
JOIN T2 ON T1.GENRE = T2.GENRE;