SELECT CATEGORY.NAME AS NAMA_KATEGORI,
	COUNT(INVENTORY_ID) AS JUMLAH_DITONTON
FROM PUBLIC.INVENTORY

LEFT JOIN FILM ON FILM.FILM_ID = INVENTORY.FILM_ID
INNER JOIN FILM_CATEGORY ON FILM_CATEGORY.FILM_ID = FILM.FILM_ID
LEFT JOIN CATEGORY ON CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID

GROUP BY CATEGORY.NAME
ORDER BY JUMLAH_DITONTON DESC
LIMIT 100